/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { ZapGettersLibrary } from "../ZapGettersLibrary";

export class ZapGettersLibrary__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ZapGettersLibrary> {
    return super.deploy(overrides || {}) as Promise<ZapGettersLibrary>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ZapGettersLibrary {
    return super.attach(address) as ZapGettersLibrary;
  }
  connect(signer: Signer): ZapGettersLibrary__factory {
    return super.connect(signer) as ZapGettersLibrary__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZapGettersLibrary {
    return new Contract(address, _abi, signerOrProvider) as ZapGettersLibrary;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "_newZap",
        type: "address",
      },
    ],
    name: "NewZapAddress",
    type: "event",
  },
];

const _bytecode =
  "0x604c602c600b82828239805160001a60731460008114601c57601e565bfe5b5030600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea165627a7a72305820591eea357c481a0b5238b9e41233db7e7a617923faed6e40566d8a0d3c6f43a90029";
