/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DatabaseInterface extends ethers.utils.Interface {
  functions: {
    "setIntArrayIndex(bytes32,uint256,int256)": FunctionFragment;
    "pushIntArray(bytes32,int256)": FunctionFragment;
    "getIntArray(bytes32)": FunctionFragment;
    "setBytes(bytes32,bytes)": FunctionFragment;
    "getNumber(bytes32)": FunctionFragment;
    "getAddressArrayLength(bytes32)": FunctionFragment;
    "getBytesArrayLength(bytes32)": FunctionFragment;
    "setBytes32(bytes32,bytes32)": FunctionFragment;
    "setNumber(bytes32,uint256)": FunctionFragment;
    "setBytesArray(bytes32,bytes32[])": FunctionFragment;
    "getAddressArray(bytes32)": FunctionFragment;
    "getBytesArrayIndex(bytes32,uint256)": FunctionFragment;
    "setString(bytes32,string)": FunctionFragment;
    "setAddressArrayIndex(bytes32,uint256,address)": FunctionFragment;
    "pushBytesArray(bytes32,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "getBytesArray(bytes32)": FunctionFragment;
    "getString(bytes32)": FunctionFragment;
    "getIntArrayLength(bytes32)": FunctionFragment;
    "getIntArrayIndex(bytes32,uint256)": FunctionFragment;
    "setStorageContract(address,bool)": FunctionFragment;
    "setBytesArrayIndex(bytes32,uint256,bytes32)": FunctionFragment;
    "getBytes32(bytes32)": FunctionFragment;
    "setIntArray(bytes32,int256[])": FunctionFragment;
    "getBytes(bytes32)": FunctionFragment;
    "pushAddressArray(bytes32,address)": FunctionFragment;
    "getAddressArrayIndex(bytes32,uint256)": FunctionFragment;
    "setAddressArray(bytes32,address[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "setIntArrayIndex",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pushIntArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumber",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressArrayLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytesArrayLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNumber",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytesArray",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytesArrayIndex",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressArrayIndex",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pushBytesArray",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBytesArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntArrayLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntArrayIndex",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStorageContract",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytesArrayIndex",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIntArray",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pushAddressArray",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressArrayIndex",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressArray",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "setIntArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNumber", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBytesArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setNumber", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBytesArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddressArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStorageContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBytesArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "StorageModified(address,bool)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StorageModified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Database extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DatabaseInterface;

  functions: {
    setIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setIntArrayIndex(bytes32,uint256,int256)"(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushIntArray(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pushIntArray(bytes32,int256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getIntArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "getIntArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    setBytes(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setBytes(bytes32,bytes)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getNumber(key: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getNumber(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAddressArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getAddressArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBytesArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getBytesArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setBytes32(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setBytes32(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNumber(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setNumber(bytes32,uint256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytesArray(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setBytesArray(bytes32,bytes32[])"(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAddressArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "getAddressArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getBytesArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setString(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setString(bytes32,string)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAddressArrayIndex(bytes32,uint256,address)"(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushBytesArray(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pushBytesArray(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    getBytesArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "getBytesArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getString(key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getString(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getIntArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getIntArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getIntArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setStorageContract(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setStorageContract(address,bool)"(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setBytesArrayIndex(bytes32,uint256,bytes32)"(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBytes32(key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getBytes32(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setIntArray(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setIntArray(bytes32,int256[])"(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBytes(key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getBytes(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pushAddressArray(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pushAddressArray(bytes32,address)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getAddressArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAddressArray(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAddressArray(bytes32,address[])"(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  setIntArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setIntArrayIndex(bytes32,uint256,int256)"(
    key: BytesLike,
    index: BigNumberish,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushIntArray(
    key: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pushIntArray(bytes32,int256)"(
    key: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getIntArray(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber[]>;

  "getIntArray(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  setBytes(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setBytes(bytes32,bytes)"(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getNumber(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  "getNumber(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAddressArrayLength(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAddressArrayLength(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBytesArrayLength(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getBytesArrayLength(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setBytes32(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setBytes32(bytes32,bytes32)"(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNumber(
    key: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setNumber(bytes32,uint256)"(
    key: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytesArray(
    key: BytesLike,
    value: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setBytesArray(bytes32,bytes32[])"(
    key: BytesLike,
    value: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAddressArray(key: BytesLike, overrides?: CallOverrides): Promise<string[]>;

  "getAddressArray(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getBytesArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getBytesArrayIndex(bytes32,uint256)"(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setString(
    key: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setString(bytes32,string)"(
    key: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAddressArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAddressArrayIndex(bytes32,uint256,address)"(
    key: BytesLike,
    index: BigNumberish,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushBytesArray(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pushBytesArray(bytes32,bytes32)"(
    key: BytesLike,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  getBytesArray(key: BytesLike, overrides?: CallOverrides): Promise<string[]>;

  "getBytesArray(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getString(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getString(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getIntArrayLength(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getIntArrayLength(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getIntArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getIntArrayIndex(bytes32,uint256)"(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setStorageContract(
    _storageContract: string,
    _allowed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setStorageContract(address,bool)"(
    _storageContract: string,
    _allowed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytesArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setBytesArrayIndex(bytes32,uint256,bytes32)"(
    key: BytesLike,
    index: BigNumberish,
    value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBytes32(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getBytes32(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  setIntArray(
    key: BytesLike,
    value: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setIntArray(bytes32,int256[])"(
    key: BytesLike,
    value: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBytes(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getBytes(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  pushAddressArray(
    key: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pushAddressArray(bytes32,address)"(
    key: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAddressArrayIndex(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAddressArrayIndex(bytes32,uint256)"(
    key: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setAddressArray(
    key: BytesLike,
    value: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAddressArray(bytes32,address[])"(
    key: BytesLike,
    value: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    setIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setIntArrayIndex(bytes32,uint256,int256)"(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pushIntArray(
      key: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "pushIntArray(bytes32,int256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getIntArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getIntArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    setBytes(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBytes(bytes32,bytes)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getNumber(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getNumber(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytesArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBytesArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBytes32(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBytes32(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setNumber(
      key: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setNumber(bytes32,uint256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytesArray(
      key: BytesLike,
      value: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setBytesArray(bytes32,bytes32[])"(
      key: BytesLike,
      value: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    getAddressArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getAddressArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getBytesArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setString(
      key: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setString(bytes32,string)"(
      key: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAddressArrayIndex(bytes32,uint256,address)"(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    pushBytesArray(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "pushBytesArray(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    getBytesArray(key: BytesLike, overrides?: CallOverrides): Promise<string[]>;

    "getBytesArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getString(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getString(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getIntArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIntArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIntArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setStorageContract(
      _storageContract: string,
      _allowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setStorageContract(address,bool)"(
      _storageContract: string,
      _allowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBytesArrayIndex(bytes32,uint256,bytes32)"(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getBytes32(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getBytes32(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setIntArray(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setIntArray(bytes32,int256[])"(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    getBytes(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getBytes(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    pushAddressArray(
      key: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "pushAddressArray(bytes32,address)"(
      key: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAddressArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setAddressArray(
      key: BytesLike,
      value: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setAddressArray(bytes32,address[])"(
      key: BytesLike,
      value: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    StorageModified(
      contractAddress: string | null,
      allowed: null
    ): TypedEventFilter<
      [string, boolean],
      { contractAddress: string; allowed: boolean }
    >;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    setIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setIntArrayIndex(bytes32,uint256,int256)"(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushIntArray(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pushIntArray(bytes32,int256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getIntArray(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getIntArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBytes(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setBytes(bytes32,bytes)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getNumber(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getNumber(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddressArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytesArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBytesArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBytes32(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setBytes32(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNumber(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setNumber(bytes32,uint256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytesArray(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setBytesArray(bytes32,bytes32[])"(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAddressArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBytesArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setString(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setString(bytes32,string)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAddressArrayIndex(bytes32,uint256,address)"(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushBytesArray(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pushBytesArray(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBytesArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBytesArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getString(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getString(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIntArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIntArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setStorageContract(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setStorageContract(address,bool)"(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setBytesArrayIndex(bytes32,uint256,bytes32)"(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBytes32(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getBytes32(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setIntArray(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setIntArray(bytes32,int256[])"(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBytes(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getBytes(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pushAddressArray(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pushAddressArray(bytes32,address)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAddressArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAddressArray(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAddressArray(bytes32,address[])"(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setIntArrayIndex(bytes32,uint256,int256)"(
      key: BytesLike,
      index: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushIntArray(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pushIntArray(bytes32,int256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getIntArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getIntArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBytes(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setBytes(bytes32,bytes)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getNumber(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNumber(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytesArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBytesArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBytes32(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setBytes32(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNumber(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setNumber(bytes32,uint256)"(
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytesArray(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setBytesArray(bytes32,bytes32[])"(
      key: BytesLike,
      value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAddressArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBytesArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setString(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setString(bytes32,string)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAddressArrayIndex(bytes32,uint256,address)"(
      key: BytesLike,
      index: BigNumberish,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushBytesArray(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pushBytesArray(bytes32,bytes32)"(
      key: BytesLike,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBytesArray(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBytesArray(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getString(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getString(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntArrayLength(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getIntArrayLength(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getIntArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setStorageContract(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setStorageContract(address,bool)"(
      _storageContract: string,
      _allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytesArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setBytesArrayIndex(bytes32,uint256,bytes32)"(
      key: BytesLike,
      index: BigNumberish,
      value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBytes32(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBytes32(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setIntArray(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setIntArray(bytes32,int256[])"(
      key: BytesLike,
      value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBytes(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBytes(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pushAddressArray(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pushAddressArray(bytes32,address)"(
      key: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAddressArrayIndex(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddressArrayIndex(bytes32,uint256)"(
      key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAddressArray(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAddressArray(bytes32,address[])"(
      key: BytesLike,
      value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
